# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='定价')),
            ],
        ),
    ]
