# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190816_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='myauthor',
        ),
        migrations.AlterModelTable(
            name='book',
            table='mybook',
        ),
    ]
