# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book2',
            table='mybook2',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='mypub',
        ),
    ]
