# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Author3',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Book3',
        ),
    ]
