# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore3', '0002_auto_20190816_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book3',
            name='author',
            field=models.ManyToManyField(to='bookstore3.Author3'),
        ),
    ]
